name: Run API Tests
on:
  push:
     branches: [main]
  workflow_dispatch:
  schedule:
   - cron: '30 2  * * *'   #8:00 AM IST
   - cron: '30 13 * * *'   #7:00 PM IST

jobs:
   run-tests:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
         uses: actions/checkout@v5.0.0
       - name: Setup Node
         uses: actions/setup-node@v5.0.0
         with:
          node-version: '22'
       - name: Install Newman
         run: |
           npm install -g newman
           npm install -g newman-reporter-htmlextra
       - name: Run Collection
         run: |
           newman run 'flow_waaranty11.postman_collection.json'
      
           
        




